### ISSUE TITLE
Empty line at the end of result when including < IfModule> tags

### ISSUE THREAD

**Issue by andreascreten** [madewithlove/htaccess.madewithlove.be#15]
> Here is an example that will give an empty button line with a strange evaluation.
> http://localhost/salerferfoon
>
> <IfModule mod_rewrite.c>
> RewriteEngine on
> RewriteRule ^$ structure.php?p=main [L]
> RewriteRule ^saloon$ structure.php?p=saloon [L]
> RewriteRule ^rules$ structure.php?p=rules [L]
> RewriteCond %{REQUEST_URI} !=^/structure.php?p=error$
> RewriteRule ^.*$ /structure.php?p=error  [R]
> </IfModule>
> 
> There is an empy line that gives \"This rule was met, the new url is http://localhost/structure.php?p=error\"

_Emailed by Fede on June 18, 2014 at 3:21 am CET_

**Comment by mogetutu** [comment]
![screen shot 2015-05-26 at 11 07 34](https://cloud.githubusercontent.com/assets/411754/7807920/bff01068-0397-11e5-9859-84e9bbb9d6f0.jpg)

**Comment by mogetutu** [comment]
This works fine now.
