### ISSUE TITLE
Implement Redirect 301 .. non-RewriteRule redirects

### ISSUE THREAD

**Issue by andreascreten** [madewithlove/htaccess.madewithlove.be#17]
See this tweet: https://twitter.com/SeanGinnaw/status/559765579603906560

**Comment by Scotchester** [comment]
:+1: 

Support for `mod_alias` rules would be most appreciated!

**Comment by WouterSioen** [comment]
@Scotchester The mod_alias `Redirect` directive has now been implemented. We might add other mod_alias directives later, but this was the most important one for the tool, so I'm going to close this issue.

**Comment by Scotchester** [comment]
Sweet, thanks!
