### ISSUE TITLE
QSA flag not working

### ISSUE THREAD

**Issue by schipa** [madewithlove/htaccess.madewithlove.be#20]
Example taken from [Apache Documentation on RewriteRule Flags](https://httpd.apache.org/docs/2.4/rewrite/flags.html#flag_qsa).

**Request url**
`http://example.com/pages/123?one=two`

**htaccess**
`RewriteRule pages/(.+) page.php?page=$1 [QSA]`

**Expectation**
`http://example.com/page.php?page=123&one=two`

**Tool output**
`http://example.com/page.php?page=123`

**Comment by andreascreten** [comment]
This should now be implemented, thanks for your feedback!

**Comment by richardbrinkman** [comment]
It's still not fixed!
Since I could not reopen this issue I created a new issue #36 but it's exactly the same issue as this one.
