### ISSUE TITLE
Crash when htaccess is commented out

### ISSUE THREAD

**Issue by greenleafmedia** [madewithlove/htaccess.madewithlove.be#21]
Hi there -

Don't think too many people will run into this, but just so you know there's a hard crash when you run a test on an htaccess file that's all commented out.  For example:

<pre>
#RewriteCond %{HTTP_HOST} !=www.domain.com [NC]
#RewriteRule ^(.*)$ http://www.domain.com/$1 [R=301,L]
</pre>

**Comment by andreascreten** [comment]
Hum, works fine here. Can you provide some screenshots?

**Comment by mogetutu** [comment]
Yeah, Also probably also change the message on the Comment class.

**Comment by greenleafmedia** [comment]
Yeah, doesn't look like it's doing it anymore.  I don't remember the exact conditions from 3 months ago, but it fine now.

**Comment by andreascreten** [comment]
Cool, thanks!
