### ISSUE TITLE
Or not working correctly 

### ISSUE THREAD

**Issue by robinjoh90** [madewithlove/htaccess.madewithlove.be#26]
The following code redirects primarydomain.com, secondarydomain.com and www.secondarydomain.com to www.primarydomain.com, but when you type primarydomain.com in the request url field the rule is marked as not met. This is not correct.

RewriteCond %{HTTP_HOST} ^primarydomain.com [NC,OR]
RewriteCond %{HTTP_HOST} ^secondarydomain.com [NC,OR]
RewriteCond %{HTTP_HOST} ^www.secondarydomain.com [NC]
RewriteRule ^(.*)$ http://www.primarydomain.com/$1 [R=301,nc,L]

![or](https://cloud.githubusercontent.com/assets/19281328/15139081/25df30e2-1694-11e6-992e-1c088e875a88.png)

It seems like you only can have one OR between each rule.

**Comment by andreascreten** [comment]
Good catch, should be fixed now!
