### ISSUE TITLE
RewriteCond %{HTTPS} don't work

### ISSUE THREAD

**Issue by 50thomatoes50** [madewithlove/htaccess.madewithlove.be#27]
RewriteCond %{HTTPS} !=on
The result is always 

> This condition was met.

thank you very much for this usefull tool

**Comment by WouterSioen** [comment]
I just double checked and this does not seem to work against apache 2.4.

These statements do work:

`RewriteCond %{HTTPS} on`
`RewriteCond %{HTTPS} off`

but I could not get any negations to work when playing around with htaccess files on apache 2.4.

This might be a feature that got dropped by apache, but you can use the working examples I posted instead.
