### ISSUE TITLE
Use Apache to evaluate

### ISSUE THREAD

**Issue by amenk** [madewithlove/htaccess.madewithlove.be#28]
Did you think about using a real apache to evaluate the rules and parsing it's log output?
Or at least using the original mod_rewrite code ?

**Comment by andreascreten** [comment]
Would make sense, we are going to investigate if this is possible. Currently we have re-written the implementation in PHP so we can provide more background information on why certain things happen.

**Comment by WouterSioen** [comment]
@amenk We probably will not do this, but we have an almost full test coverage of all the implemented rules and all tests run both against the application and against apache.

This means that we will have the exact same output in most of the cases and that if bugs arise, we can easily fix them forever by adding a test that has to pass against both apache and our application.

I'll close this issue. Thanks for the idea though.
