### ISSUE TITLE
rewritecond backreference issue?

### ISSUE THREAD

**Issue by sebastienratez** [madewithlove/htaccess.madewithlove.be#29]
Hi,

I put that with a question mark because really, I'm not sure.

I tried this:

RewriteCond %{HTTP_HOST}                ([^\.]+)\.domain\.io                [NC]
RewriteRule (.*)                                %1                                            [L]

against "bibi.domain.io/qweqwe.php"

Result is "bibi.domain.io/bibibibi"

Why is the %1 group duplicated?
On another note, %0 should return something apparently (http://httpd.apache.org/docs/current/mod/mod_rewrite.html#rewritecond) but I could not make it work.

Thanks for the help :)

**Comment by andreascreten** [comment]
This should be fixed now, thanks for the feedback!
