### ISSUE TITLE
Does it work?

### ISSUE THREAD

**Issue by mejmo** [madewithlove/htaccess.madewithlove.be#31]
Maybe I am do not getting how this tool works, but it seems to not match the regex in any case. 

Example:

`RewriteEngine on`
`RewriteRule   ^/$  /e/www/  [R]`

Input:

`http://test/`

This rule was not met.

**Comment by andreascreten** [comment]
As far as I know this is the correct behaviour. The regex starts looking for everything after the first slash after the hostname. The correct rule for this would be `RewriteRule ^$ /e/www/`.
