### ISSUE TITLE
Wrong new url in debugging info?

### ISSUE THREAD

**Issue by mgrn0** [madewithlove/htaccess.madewithlove.be#32]
I think there might be an error displayed in the debugging info:

When I test some htaccess rules with the following lines:

Test-Url: 

> http://sub.domain.info

htaccess-Rules:

> RewriteCond %{HTTP_HOST} ^sub.domain.info$
> RewriteRule (.*) http://www.anotherdomain.com/$1 [R=301,L]

the debugging info displayed is:

> The new url is http://sub.domain.info/
> Test are stopped, a redirect will be made with status code 301.

Should not this redirect to http://www.anotherdomain.com ? 

![screenshot_2016-08-01_13 42 18](https://cloud.githubusercontent.com/assets/3019226/17292997/d50bb802-57ed-11e6-9585-5115d8d7e0d9.png)

(sorry in case I should be wrong, but my webserver does indeed redirect to www.anotherdomain.com tested with these values)

**Comment by WouterSioen** [comment]
I tested this again and this works perfectly fine now (we did quite some refactoring lately).
Thanks for the bug report!
