### ISSUE TITLE
Button "this is madewithlove on friday" does not work

### ISSUE THREAD

**Issue by mgrn0** [madewithlove/htaccess.madewithlove.be#33]
Not a big thing, but clicking on the "this is madewithlove on friday" button in the lower right corner opens a slide-in panel with a 404 error page from GitHub.

![screenshot 2016-08-01 at 13 52 04 pm](https://cloud.githubusercontent.com/assets/3019226/17293225/576f1f9a-57ef-11e6-81cf-68c7a50a1b3c.png)

**Comment by andreascreten** [comment]
Should be good now.
