### ISSUE TITLE
Don't do ${\d} references with numbers higher than 9.

### ISSUE THREAD

**Issue by hannesvdvreken** [madewithlove/htaccess.madewithlove.be#35]
![image](https://cloud.githubusercontent.com/assets/1410358/19677984/21027070-9a9c-11e6-9a8a-ef2f8930eb96.png)

`$10` should not be used.

Reported here: https://twitter.com/madewithlove/status/790789904322232320

**Comment by WouterSioen** [comment]
Fixed as can be seen in https://htaccess.madewithlove.be?share=02ef3cf3-7cfe-5aac-8459-a99d592ca31f

**Comment by hannesvdvreken** [comment]
🦌🎁🎄 thx
