### ISSUE TITLE
QSA flag does not seem to be supported

### ISSUE THREAD

**Issue by richardbrinkman** [madewithlove/htaccess.madewithlove.be#36]
An .htaccess file containing a line like this does not seem to be supported:
```apache
RewriteRule ^(.*)$ index.php?route=$1 [NC,L,QSA]
```

A URL like http://myserver.com/myroute?myvar=myvalue should be redirected to http://myserver.com/index.php?route=myroute&myvar=myvalue. The test tool gives http://myserver.com/index.php?route=myroute, thus forgetting the variable myvar and its value.

**Comment by themagnifico** [comment]
Having the same problem: QSA not working

**Comment by themagnifico** [comment]
From this blog post: https://simonecarletti.com/blog/2009/01/apache-rewriterule-and-query-string/

The last example '_Append new query to original query_' is not working 

**Keep original query (default behavior)**
`RewriteRule ^page\.php$ /target.php [L]`
from http://example.com/page.php?foo=bar
to   http://example.com/target.php?foo=bar

**Discard original query**
`RewriteRule ^page\.php$ /target.php? [L]`
from http://example.com/page.php?foo=bar
to   http://example.com/target.php

**Replace original query**
`RewriteRule ^page\.php$ /target.php?bar=baz [L]`
from http://example.com/page.php?foo=bar
to   http://example.com/target.php?bar=baz

**Append new query to original query _(Not working)_**
`RewriteRule ^page\.php$ /target.php?bar=baz [QSA,L]`
from http://example.com/page.php?foo=bar
to   http://example.com/target.php?foo=bar&bar=baz

**Comment by andreascreten** [comment]
This should be solved now. Thanks for the feedback guys!
