### ISSUE TITLE
Support for ENV?

### ISSUE THREAD

**Issue by amiga-500** [madewithlove/htaccess.madewithlove.be#37]
For example:  http://domain.com/?foo=4&sunamy=4
```
    RewriteRule ^ - [E=MY_QUERY_STRING:%{QUERY_STRING}]
    RewriteRule ^ - [E=MY_QUERY_STRING:%1%2]
    RewriteCond %{ENV:MY_QUERY_STRING} ^(.+?&|)foo.*?(&.*|)$ [NC]
    RewriteRule ^ - [E=MY_QUERY_STRING:%1%2]
    RewriteCond %{ENV:MY_QUERY_STRING} ^(.+?&|)sunamy=.*?(&.*|)$ [NC]
    RewriteRule ^ - [E=MY_QUERY_STRING:%1%2]
```
![htaccess_tester_-_madewithlove_-_2016-12-26_01_31_06](https://cloud.githubusercontent.com/assets/5191497/21476910/06b42d5e-cb0b-11e6-8c5f-560385a31641.png)

**Comment by WouterSioen** [comment]
@amiga-500 our latest release added support for basic environment variables. You can see an example of this here: https://htaccess.madewithlove.be?share=39cacebc-ea0f-576b-9b1c-e29824255a8a
