### ISSUE TITLE
RewriteRule "^/foo$" "/bar" (Apache Docs)

### ISSUE THREAD

**Issue by antibrick** [madewithlove/htaccess.madewithlove.be#38]
Good evening!

First of all: thanks for your cool tool!

Maybe I'm getting something wrong at the moment.
According to the current Apache Docs the rule _RewriteRule "^/foo$" "/bar"_ should redirect a request from _http://example.com/foo_ to _/usr/local/apache2/htdocs/bar_ (it's the example from https://httpd.apache.org/docs/current/rewrite/intro.html#rewriterule).

The tool always tells me that the rule didn't met... So what's going wrong here?

Kind regards! + Thank you!
Yorick

(Please excuse my weak English – I'm a student from Germany...)

**Comment by andreascreten** [comment]
Looks like Apache 2.4 uses quotation marks around rule elements now, which is something we do not support. It was not the case in the previous versions: https://httpd.apache.org/docs/2.2/rewrite/intro.html#rewriterule. We will think about how we can reflect this change in the tester. Do the rules also work without the quotation marks, do you know that?

**Comment by pooley182** [comment]
It's not the quote marks that stop this from matching. It's the caret at the start of the regex.

as an example,for a test URL of `www.example.com/foo`
`RewriteRule "/foo" "/bar" [R]` and `RewriteRule /foo "/bar" [R]` both match
where as `RewriteRule "^/foo" "/bar" [R]` and `RewriteRule ^/foo "/bar" [R]` both fail to match.

**Comment by WouterSioen** [comment]
I double checked this against an apache instance and:

`RewriteRule "^/foo" "/bar" [R]` does **not** match for `www.example.com/foo`
`RewriteRule ^/foo /bar [R]` does **not** match for `www.example.com/foo`
`RewriteRule "^foo" "/bar" [R]`matches for `www.example.com/foo`
`RewriteRule ^foo /bar [R]` matches for `www.example.com/foo`

This is also exactly how the htaccess tester has it implemented. going to close this issue.

**Comment by pooley182** [comment]
I've just tested those same rules on apache 2.4.18 and 2.4.38 and they all match.
It's also what is described in the apache 2.4 documentation.

**Comment by WouterSioen** [comment]
Weird, I'm going to double check this again, but I have an automated test suite that runs against both apache and the htaccess tester and these examples seem to behave exactly the same in both environments.

**Comment by pooley182** [comment]
Apologies, this can indeed be closed, and is actually an oddity in the way apache processes rules in it's virtualhost config files versus how it processes them in the .htaccess

Starting with a preceding slash is only valid in a virtualhost config file and not within the context of a htaccess file.

**Comment by WouterSioen** [comment]
Okay, thanks for figuring out why we had different results. The tester is indeed testing how it behaves in an htaccess file and not in the virtualhost file.
