### ISSUE TITLE
Rewrite to HTTPS doesn't give correct output url

### ISSUE THREAD

**Issue by Hakaari** [madewithlove/htaccess.madewithlove.be#40]
> #Options +FollowSymLinks
RewriteEngine On
RewriteCond %{HTTPS} !on
RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]

The output role should be with https, but it shows without it.

In debugging info, it gives following output 

> The new url is http://www.domain.com/
Test are stopped, a redirect will be made with status code 301

the output url is without https also

> http://www.domain.com

**Comment by Boboss74** [comment]
Maybe you should have used
`RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]`

**Comment by WouterSioen** [comment]
This should be fixed now! There was an issue where `(.*)` didn't work as intended.
