### ISSUE TITLE
RewriteBase should not be inserted into absolute paths

### ISSUE THREAD

**Issue by joshstrike** [madewithlove/htaccess.madewithlove.be#41]
Consider:
```
RewriteBase /foo/
RewriteRule ^(.*)bar$ $1index.php [L]
```
In the tester, the above example correctly inserts the RewriteBase into the relative path if necessary.
http://test.com/bar > http://test.com/foo/index.php
http://test.com/foo/bar > http://test.com/foo/index.php

However:
```
RewriteBase /foo/
RewriteCond %{HTTP_HOST} !^www\.(.*)$ [NC]
RewriteRule ^(.*)$ http://www.%{HTTP_HOST}/$1 [L,R=301]
```

In this case, the tester shows:
http://test.com > http://www.test.com/foo//

This is incorrect, since Apache doesn't apply RewriteBase when rewriting or redirecting to an absolute path.

**Comment by andreascreten** [comment]
Thanks for letting us know, we will investigate this.

**Comment by WouterSioen** [comment]
This seems to be fixed
