### ISSUE TITLE
PHP Errors are showing

### ISSUE THREAD

**Issue by mattferderer** [madewithlove/htaccess.madewithlove.be#42]
I'm not sure if you want this, but your php errors are showing. I can send you a screenshot if you want or post one here.

**Comment by xavierbarbosa** [comment]
Thanks for letting us know. Seems we have some misconfiguration. Will be taking a look shortly.

**Comment by NiketMalik** [comment]
Just a heads up. They are still showing.

**Comment by xavierbarbosa** [comment]
Thanks guys! Should be good now.
