### ISSUE TITLE
Double escaped sequences aren't matched

### ISSUE THREAD

**Issue by svenluijten** [madewithlove/htaccess.madewithlove.be#43]
`.htaccess` rules generated by some generators around the web generate output like this:

```conf
RewriteRule ^foo\-bar\-baz$ /new [L,R=301]
```

This works as expected on Apache/2.4.6, where `/foo-bar-baz` gets redirected to `/new`. However, http://htaccess.mwl.be/ doesn't match the URL `/foo-bar-baz`. Instead, it expects the literal URL `/foo\-bar\-baz` (including the backslashes!).

This is probably due to how Apache handles escaping URLs, it just strips all the `\` characters from the URL somewhere in the process. As far as I'm aware, we can do just that after escaping the necessary characters in this tool.

It's a bit of an edge-case, but multiple generators have generated this output, so it'd only make sense for this checker to detect these cases.

**Comment by WouterSioen** [comment]
We did quite some refactoring and testing lately and it seems like this bug is fixed now.

Thanks for the bug report!
