### ISSUE TITLE
Not showing redirect loop error

### ISSUE THREAD

**Issue by martin-enavn** [madewithlove/htaccess.madewithlove.be#44]
When there is a redirect loop error it is not shown, either show it in URL(eg. http://mydomain.com/shop/shop/shop...) or in debug info.

**Comment by andreascreten** [comment]
This would mean we have to run the test again and end up in a loop ourselves ;-)

Let us think about possible ways to visualise this.

**Comment by WouterSioen** [comment]
Closing this in favour of #60
