### ISSUE TITLE
%{SERVER_NAME} is not supported

### ISSUE THREAD

**Issue by jendrikw** [madewithlove/htaccess.madewithlove.be#46]
Title says all.

**Comment by andreascreten** [comment]
Yeah this is pretty hard, because there are a lot of options with it.
More info: http://httpd.apache.org/docs/current/mod/mod_rewrite.html#rewritecond

We will think about how we could do that!

**Comment by WouterSioen** [comment]
We've added a SERVER_NAME field under "advanced fields" which does the trick now.
