### ISSUE TITLE
"This condition was met." -  highlighting

### ISSUE THREAD

**Issue by StevenSchoening** [madewithlove/htaccess.madewithlove.be#48]
When a condition was met or not everything is marked in red.
This is a little bit confusing and i suggest that the conditions which were met are marked in green.

**Comment by WouterSioen** [comment]
@StevenSchoening Thanks for the report. We've added basic color coding in the application (rule/condition met = green, rule/condition not met = red, rule/condition not reached => no color).

All feedback on it is welcome, but I'll close the issue for now.
