### ISSUE TITLE
source code available ?

### ISSUE THREAD

**Issue by dandumit** [madewithlove/htaccess.madewithlove.be#49]
HI,
I would like to use your interpreter in conjunction with https://github.com/dugwood/clickheat
So I could see what pages are accessed by user/server.
Thank you,
Daniel

**Comment by WouterSioen** [comment]
Hi Daniel,

I'm sorry but we won't be able to make the source code public at the moment.
We are currently focussing our efforts on making the code more bugfree, but as this is an unpaid side project, we don't have the time to clean up and decouple the code to extract in a reusable open source package at the moment.

Thanks for the interest though and good luck with clickheat.

Wouter
