### ISSUE TITLE
Make tests sharable

### ISSUE THREAD

**Issue by andreascreten** [madewithlove/htaccess.madewithlove.be#5]
> I have a wish, Could you make your tool like jsfiddle - means temporary saveable, with a link to share and discuss the result.

_[Filed by Suther on Mon, 19 Aug 2013 20:04:11 CET](http://madewithlove.be/abob/2011/04/simple-htaccess-tester/#comment-3789)_

**Comment by sepehr** [comment]
+1

**Comment by WouterSioen** [comment]
The sharing part already exists. Discussions on it don't. Is this something we still want to do? I guess a focus on getting the tester feature complete and bugfree is more important?
