### ISSUE TITLE
Slim Application Error

### ISSUE THREAD

**Issue by jerome2710** [madewithlove/htaccess.madewithlove.be#51]
`%` somewhere in the provided htaccess breaks the application. This was no problem some time ago.

For instance:

```
# Force www
RewriteCond %{HTTP_HOST} !^www\.
RewriteRule .? https://www.%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
```

**Comment by WouterSioen** [comment]
@jerome2710 can you share the snippet you tested (you can use the `share` button next to the `test` button).

I tried this with the snippet you pasted here and didn't get an application error.

**Comment by WouterSioen** [comment]
Okay, I could reproduce when I did put a percentage sign after `%{HTTP_HOST}`, we'll look into it.

Thanks for the bug report!

**Comment by jerome2710** [comment]
I see, the first case (percentage in front of `%{HTTP_HOST}`) only occurs when the condition matches: https://htaccess.mwl.be?share=7ad70d54-f4ba-56d6-82d2-2cd4b8248e7f.

**Comment by WouterSioen** [comment]
@jerome2710 If you go to the shared link again, it should be fixed now. Thanks for the bug report!
