### ISSUE TITLE
Don't generate the rewrite url

### ISSUE THREAD

**Issue by lbarboni** [madewithlove/htaccess.madewithlove.be#52]
Input url:
https://www.domaintest.com/it_it/news/tag/aereo/

Rules:
`RedirectMatch 301 ^([a-z_]+)/catalog/product/view/id/(.*)/s/(.*)/category/(.*)$ /shop/$1/$3.html`
`RedirectMatch 301 ^([a-z_]+)/news/tag/(.*) /$1/journal/tag/$2`
`RedirectMatch 301 ^([a-z_]+)/(.*)/(.*)/(.*)/(.*)$ /shop/$1/$5`
`RedirectMatch 301 ^([a-z_]+)/(.*)/(.*)/(.*)$ /shop/$1/$4`
`RedirectMatch 301 ^([a-z_]+)/(boy|girl)/(.*)$ /shop/$1/$3`
`RedirectMatch 301 ^([a-z_]+)/all-products/(.*)$ /shop/$1/$2`
`RedirectMatch 301 ^([a-z_]+)/(naturino|falcotto)-([a-z0-9-]+).html$ /shop/$1/$2-$3.html`
`RedirectMatch 301 ^([a-z_]+)/news/[0-9]{4}/[0-9]{2}/[0-9]{2}/(.*) /$1/journal/$2`

Output url:
https://www.domaintest.com/it_it/news/tag/aereo/

I expected it to be:
https://www.domaintest.com/it_it/journal/tag/aereo/

Thank you for this fantastic tool

**Comment by WouterSioen** [comment]
@lbarboni There is some bug in the tool, but it's not exactly how you are describing it. I tested the failing RedirectMatch on an empty server only running apache 2.4 and I added this `.htaccess` file:

```
RewriteEngine On
RewriteBase /
RedirectMatch 301 ^([a-z_]+)/news/tag/(.*) /$1/journal/tag/$2
```

When I then go to `/it_it/news/tag/aereo/`, the RedirectMatch doesn't even match.

You should remove the `^` in the beginning of your RedirectMatch or add a `/` after the caret (probably the better option) thus `RedirectMatch 301 ^/([a-z_]+)/news/tag/(.*) /$1/journal/tag/$2` to make the RedirectMatch match.

The generated output url in our application is wrong though, so I'll try to fix the bug in the system too asap.

I hope you're already able to make your RedirectMatch-es work on your projects though.

**Comment by WouterSioen** [comment]
@lbarboni I found the cause of the issue and was able to fix it. You can find your RedirectMatches in the correct format (containing the slashes) here: https://htaccess.mwl.be?share=2745a903-aa95-5baa-9920-fb6737847a6e

I ran the snippet against apache and it has the exact same output as the application now.

Thanks for the bugreport!
