### ISSUE TITLE
SSL Certificate for htaccess.madewithlove.be

### ISSUE THREAD

**Issue by Der-Alex** [madewithlove/htaccess.madewithlove.be#54]
Hi. I came across your htaccess tester. It's great. 
Could you add a SSL certificate to your subdomain? 

Regards, Alex

**Comment by WouterSioen** [comment]
Hi Alex,

Thanks for the bug report. It looks like the automatic renewing of our SSL certificates through let's encrypt failed. I did set-up a new SSL key though and we're looking into automatically renewing it again.

Kind Regards,

Wouter
