### ISSUE TITLE
Double slash in not shown in the output url

### ISSUE THREAD

**Issue by meijdenmedia** [madewithlove/htaccess.madewithlove.be#56]
Following input should have this output `https://domain.com//nl/product/name-of-product?zip_code=2000`

https://htaccess.madewithlove.be?share=7ded2ba7-1ecb-5c50-8616-3033296e6f35

**Comment by WouterSioen** [comment]
@meijdenmedia Are you sure this is the case?

I just tested your scenario against an actual apache server and it returned the exact same result as the htaccess tester returns.
