### ISSUE TITLE
Prestashop saves the host (base URI)

### ISSUE THREAD

**Issue by matt-matt1** [madewithlove/htaccess.madewithlove.be#58]
In my .htaccess is the line:
RewriteRule . - [E=REWRITEBASE:/]
Judging by the context, I think it saves the base of the URL, for use later:
RewriteRule ^api/(.*)$ %{ENV:REWRITEBASE}webservice/dispatcher.php?url=$1 [QSA,L]
(a subsequence line, where the environment variable is used).

So I successfully made alterations (and additions) using that logic:
RewriteRule ^inv/$ %{ENV:REWRITEBASE}simple/20170702/ [L,NC]

However the tester [wrongly] displayed the output by replaced the part with the literal string:
.../%{ENV:REWRITEBASE}...

This is not common as far I know, so I'm not surprised that you didn't implement this.

**Comment by WouterSioen** [comment]
Closing in favour of #37

**Comment by WouterSioen** [comment]
@matt-matt1 thanks for the report, our latest release fixed this, as you can see in this sample:

https://htaccess.madewithlove.be?share=a331357c-f200-5013-8dbc-15491cf47563
