### ISSUE TITLE
The [C] or [chain] flag is not supported

### ISSUE THREAD

**Issue by tcnweb** [madewithlove/htaccess.madewithlove.be#61]
I tried your very helpful tool with the following snippet:
```
# Block any script that includes a <script> tag in URL.
RewriteCond %{QUERY_STRING} (<|%3C)([^s]*s)+cript.*(>|%3E) [NC]
# Return 403 Forbidden header and show the content of the root home page
# TCN: But not for legacy TCN Forum URLs
RewriteRule !^(/*)forum/index.php? - [C]
RewriteRule .* index.php [F]


# mod_rewrite rules in order to match
# patterns given in rewrite_patterns.txt

RewriteCond %{HTTP_HOST} ^.*\.transalpclub.nl [NC]
RewriteRule ^(.*)$ https://transalpclub.nl/$1 [L,NE,R=301]

RewriteCond %{HTTP_HOST} ^.*itt2018.nl [NC]
RewriteRule ^.*$ - [G,L]

RewriteCond %{HTTP_HOST} ^(?:[0-9]{1,3}\.){3}[0-9]{1,3}$
RewriteRule ^.*$ - [F,L]

RewriteCond %{REQUEST_URI} ^(/*)forum/index.php? [NC]
RewriteRule ^.*$ - [G,L]
```
However the chained rule does not work as expected. According to the [C|chain documentation](https://httpd.apache.org/docs/current/rewrite/flags.html#flag_c) the following rule should be skipped if the chained rule does not match. 

Debugging output shows the following rule being processed:
![output](https://user-images.githubusercontent.com/48201201/53971446-3b75f300-40fd-11e9-9d2d-19447bd0eb92.png)

I'm kinda at the end of the road since the S|skip flag is not implemented either.

**Comment by WouterSioen** [comment]
@tcnweb We added support for the chain flag in the application, thanks for the suggestion.
