### ISSUE TITLE
The Tester appears to allow invalid spaces

### ISSUE THREAD

**Issue by Pikamander2** [madewithlove/htaccess.madewithlove.be#63]
The Tester seems to accept invalid filepaths that contains spaces.

For example, consider this RewriteRule:

`RewriteRule ^authors/Foo\+Foo$ /Bar Bar? [L,R=301]`

The Tester considers that to be a valid rule that will redirect `http://example.com/authors/Foo Foo` to `http://example.com/authors/Bar Bar`

But when you try it on an actual server, the site will throw a 500 Internal Error because of the spaces.

In order for the path to work, the spaces have to be escaped with a backslash. So the proper rule would be:

`RewriteRule ^authors/Foo\+Foo$ /Bar\ Bar? [L,R=301]`

I think it would be nice if the Tester called this out as invalid, or at least warned the user about it.

**Comment by WouterSioen** [comment]
@Pikamander2 thanks for the bug report, we've implemented a fix for this bug.
