### ISSUE TITLE
This test string is not supported: "%{HTTP_HOST}"

### ISSUE THREAD

**Issue by wilr** [madewithlove/htaccess.madewithlove.be#67]
Perhaps just a text field for populating HTTP_HOST or just take the base domain of the requested URL?

**Comment by WouterSioen** [comment]
Can you maybe give an example of how you tested this?

The HTTP_HOST apache variable is supposed to be supported.

**Comment by WouterSioen** [comment]
@wilr as you can see in [this example](https://htaccess.madewithlove.be?share=06da583e-516b-5031-989d-daa2a6e36524), HTTP_HOST correctly works.

I'll close this for now. If you have an example of an htaccess file where it does not work, feel free to re-open this issue with an example.
