### ISSUE TITLE
Reporting error on valid RewriteCond string

### ISSUE THREAD

**Issue by cocest** [madewithlove/htaccess.madewithlove.be#68]
The *htaccess tester* is reporting an error (This test string is not supported) on valid *RewriteCond* string. The sample *htaccess* configuration text entered is shown below:

    RewriteEngine on
    RewriteCond "$1.php" -f
    RewriteRule "^(.*)\.html$" "$1.php"

**Comment by WouterSioen** [comment]
We currently don't support file attribute tests on a RewriteCond, because our tester can't know if a certain path is a file path or another route. That's why this piece of code is reported as unsupported.

Thanks for the bug report though.
