### ISSUE TITLE
QUERY_STRING problem

### ISSUE THREAD

**Issue by petrahu** [madewithlove/htaccess.madewithlove.be#69]
I would like to block access to `https://mysite.tld/` with a QUERY_STRING, e.g. `https://mysite.tld/?huhu=blabla`. This code works in my .htacces:

```
RewriteCond %{QUERY_STRING} ^$   # QUERY_STRING does not exist?
RewriteRule ^$ /entry/ [L]       # OK when not.
RewriteRule ^$ - [R=403,L]       # If yes, disable access
```

The tester does not recognize `RewriteCond %{QUERY_STRING} ^$`.

**Comment by WouterSioen** [comment]
Hi @petrahu 

Thanks for the bug report, we've fixed this in our latest release!
