### ISSUE TITLE
[Feature request] Keep original format

### ISSUE THREAD

**Issue by savioret** [madewithlove/htaccess.madewithlove.be#70]
I'm testing large .htaccess files and the test button automatically removes comments and extra newlines, breaking the original format of the file, and making it harder to read.

It would be great an option not no cleanup the code on test.

Thank you.

**Comment by WouterSioen** [comment]
Hi @savioret 

Thanks for the report. Do you have an example of an .htaccess file with which you encountered this? This makes it slightly easier for us to test this.

Best Regards

Wouter

**Comment by savioret** [comment]
Sure.
[sample-htaccess.txt](https://github.com/madewithlove/htaccess.madewithlove.be/files/3843376/sample-htaccess.txt)

And here's a snap of how it shows after the first [test] submit. As you can see all comments and extra line-breaks have been removed.

![image](https://user-images.githubusercontent.com/5497332/68801879-33435f80-065d-11ea-875f-5da1f228f8b9.png)

Thanks !

**Comment by WouterSioen** [comment]
Thanks! I'll look into it

**Comment by WouterSioen** [comment]
@savioret as you can see in https://htaccess.madewithlove.be?share=975c53bd-f299-56b6-bfde-aa0a107fff51, we now don't manipulate the content of the htaccess textarea anymore.

**Comment by savioret** [comment]
That update is really helpful, thank you sooo much !
