### ISSUE TITLE
domain redirect rule adds 443 port at the end.

### ISSUE THREAD

**Issue by aurovrata** [madewithlove/htaccess.madewithlove.be#71]
If I add this rule for my htaccess

`RewriteRule` ^.* http://example.com/ [L,R]`

the tester redirects to,

`http://example.com:443/`

**Comment by WouterSioen** [comment]
Good catch, we didn't encounter this one yet. I'll take a look at fixing it

**Comment by WouterSioen** [comment]
Hi @aurovrata We've fixed this issue now, thanks for the report!
