### ISSUE TITLE
Straight comparison doesn't seem to be working (=)

### ISSUE THREAD

**Issue by silviuvulcan** [madewithlove/htaccess.madewithlove.be#76]
The = comparator ( straight comparison) doesn't seem to be working.

Example:

Testing for http://www.example.com/

````apache
RewriteCond %{HTTP_HOST} =www.example.com [NC]
````

Is not matched, though it matches fine when tested on my server.

Link to test: https://htaccess.madewithlove.be?share=9f37488a-6a3d-54e7-99b8-3350160aad6e

**Comment by WouterSioen** [comment]
@silviuvulcan interesting, I didn't know this option existed, I'll check how easy it is to add!

**Comment by WouterSioen** [comment]
@silviuvulcan The fix for this + for the other "lexicograhpical comparisons" (<, >, <= and >=) is now deployed to production.

Thanks for the feature request and for helping us improve this tool!
