### ISSUE TITLE
Filter only met conditions or rules

### ISSUE THREAD

**Issue by savioret** [madewithlove/htaccess.madewithlove.be#77]
For large htaccess files with hundreds of rules, it would be great to have a button/switch just to show those those that are met.
It's a way to have a quick view of them.

Something like:
![image](https://user-images.githubusercontent.com/5497332/83402939-03e11e00-a408-11ea-9b73-a27581f714fc.png)

Thanks

**Comment by WouterSioen** [comment]
Hi @savioret 

First of all, thanks for sending in this idea.

While I understand the idea behind the feature request, I feel like this would not be very useful in 90% of the use cases and thus only clutter the UI.

We try to keep our tool as simple as possible to make sure it's very easy to use for everyone. I feel like the colors in the output already nicely show wich conditions/rules are met and which not, so I'd rather not implement this feature for now.

If there'd be more people requesting this exact same thing, we might consider it, but I'll close this for now.
