### ISSUE TITLE
https tests via SERVER_PORT seem not to be detected

### ISSUE THREAD

**Issue by damaddin** [madewithlove/htaccess.madewithlove.be#80]
**Describe the bug**

It seems that the commonly used SERVER_PORT variable is not set when using a https:// url.

**Expected behavior**

Given these rules (copy&paste from somewhere on the Internet):

RewriteEngine on
RewriteCond %{SERVER_PORT} !^443$
RewriteRule (.*) https://%{HTTP_HOST}/$1 [R=301,L]

I would not expect a 301 redirect to be issued given https://www.example.org. However this is the actual result:

The new url is https://www.example.org/
Test are stopped, a redirect will be made with status code 301

**Reproduce link**

https://htaccess.madewithlove.be?share=fd5da363-dcf4-4c02-a93a-10bb32bb6c50

**Comment by WouterSioen** [comment]
Frist of all, thanks for the bug report. Sorry for the long wait (I was off on parental leave and on holidays most of the last two months), but I finally implemented a fix for this. When you click the reproduce link, you can see that this now works correctly.

Best regards and thanks!
