### ISSUE TITLE
This test string is not supported: %{REMOTE_ADDR}

### ISSUE THREAD

**Issue by 8p-design** [madewithlove/htaccess.madewithlove.be#81]
Would be nice to support REMOTE_ADDR At least for the syntax.

**Comment by jdrieghe** [comment]
Hi @8p-design !
We just added support for this in the UI: https://htaccess.madewithlove.be?share=cef9e2fe-ffdc-4512-96da-cd5939aa1670

Support in our [API client](https://github.com/madewithlove/htaccess-api-client) and [CLI tooling](https://github.com/madewithlove/htaccess-cli) will be coming this week.

Thanks for the feature suggestion.
