### ISSUE TITLE
have you considered a cli edition of this tool? being able to have tests in a CI/CD pipeline would be awesome.

### ISSUE THREAD

**Issue by JoSSte** [madewithlove/htaccess.madewithlove.be#85]
**Is your feature request related to a problem? Please describe.**
Sometimes you "just" create a *minor* change to .htaccess and commit it, without visiting your excellent site.

**Describe the solution you'd like**
I'd like to be able to test that certain predefined URLs work after a change (like testcases) so that the CI/CD system can catch errors  in .htaccess before deployment.

**Comment by jdrieghe** [comment]
Hi @JoSSte.
We **did** consider a CLI version of our tool. It's right here: https://github.com/madewithlove/htaccess-cli
For ease of integration, we even created a GitHub Action for it: https://github.com/madewithlove/htaccess-cli-github-action
