### ISSUE TITLE
Redirect With Folder Not Working?

### ISSUE THREAD

**Issue by ghost** [madewithlove/htaccess.madewithlove.be#87]
**Describe the bug**
Testing ".htaccess" file "Redirect 301 /foo/bar.php /index.html" with query "http://example.com/foo/bar.php" shows it not being hit. Whereas testing "Redirect 301 /bar.php /index.html" with query "http://example.com/bar.php" shows it being hit.

**Expected behavior**
I don't really know what I'm doing, so I might have made some mistake, but in real life, both seem to be hit, so this should do the same. 

**Reproduce link**
[https://htaccess.madewithlove.com?share=9db717eb-2fda-489c-80bc-bbf170ec0a88](https://htaccess.madewithlove.com?share=9db717eb-2fda-489c-80bc-bbf170ec0a88)

**Comment by WouterSioen** [comment]
Hi @agatha2 

Thanks for your bug report with the reproducible link. We were able to track down the bug and release a new version that fixes it.
